e2e: Fix e2e test case naming to match ginkgo conventions
This commit aims to adhere to ginkgo standards which is flagged in the recent versions

Output from proc 2:
  ERROR: E2E suite initialization was faulty, these errors must be fixed:
  ERROR: dynamic_provisioning.go:380: trailing or leading spaces are unnecessary and need to be re
moved: "should create a volume on demand and resize it "